### ISSUE TITLE
Pulseaudio support

### ISSUE THREAD

**Issue by danboid** [stargateaudio/stargate#12]
I have been unable to get any sound from the VA synth. I have tried using my laptops onboard soundcard and a USB soundcard but neither produced any audio.

I'm running Pulseaudio under Ubuntu 20.04. Do you plan to support PA?

**Comment by stargateaudio** [comment]
I suspect this is because the `pasuspender` utility is missing from your system.  Did you install the official Ubuntu Stargate package, or build from source? Can you please confirm if the following command works?
```
pasuspender sleep 3
```

**Comment by danboid** [comment]
Yep, pasuspender is installed and works as described.

When I have the VA synth plugin window open and in focus, should I be abler to preview notes by pushing keys on the keyboard (QWERTYUIOP and the numbers above at least)? I also expect I should hear something when I click on notes on the keyboard to the left of the MIDI editor window?

Is there a virtual midi keyboard window?

**Comment by stargateaudio** [comment]
I have plans to introduce some kind of virtual midi keyboard in the near future.  Still working out the design.  Using the top row of keys seems reasonable and probably something that can be done in the short term.  At the moment, I am heads down on fixing all of the various bugs and packaging issues that invariable get discovered when software is released to the masses, but I will try to squeeze in at least the QWERTYUIOP MIDI keyboard as soon as I can.

As far as the original issue, was it just that there was no sound because of you were expecting a virtual MIDI keyboard feature and there was none?  Or is there a legitimate audio issue with pulseaudio, can the sequencer play back notes through VA1 and output sound?  If not, what happens when you try?

**Comment by danboid** [comment]
Yes definitely no sound because I drew several notes on the MIDI track after adding a synth to it, pushed play and heard nothing. I'm presuming there's no extra routing required and its not muted by default.

**Comment by stargateaudio** [comment]
Does the playback cursor move when you press the "play" button?  If it's not moving, then the audio back end is not active (or being used by something else).  If it is moving, and the peak meters show sound, but you don't hear anything, then there are a few different issues that could be.

**Comment by jagoly** [comment]
Seem to be having the same issue, but on arch linux. Issue is as you describe above, the cursor moves but I can't hear anything. There are a lot of warnings and errors in the terminal, but not sure what if anything is relevant. I've tried all of the available devices, all give the same result, except for "default" and "pulse", where as expected the cursor doesn't move at all.

**Comment by jagoly** [comment]
also probably not related, but changing the device from within the main application, after the program restarts, it seems to just freeze after opening the splash screen window, and I have to manually kill python3

**Comment by danboid** [comment]
OK I have got sound output working with the VA synth. I had added the plugin to the Main track instead of the track I had added a MIDI clip to so user error.

**Comment by stargateaudio** [comment]
> Seem to be having the same issue, but on arch linux. Issue is as you describe above, the cursor moves but I can't hear anything. There are a lot of warnings and errors in the terminal, but not sure what if anything is relevant. I've tried all of the available devices, all give the same result, except for "default" and "pulse", where as expected the cursor doesn't move at all.

Please send me the errors and warnings.  Or you can just send me the logs in `~/stargate/log/*` (either attach here, or send them to me privately in Discord).  Also make sure it's the same issue danboid had where you added a MIDI instrument to the main track and a MIDI item to a different track.

> OK I have got sound output working with the VA synth. I had added the plugin to the Main track instead of the track I had added a MIDI clip to so user error.

Great, glad it's working for you :-) .  I'll think of ways to make this more obvious that the correct track needs to be selected in the plugin rack.  Also, FYI, you can go to the track in the sequencer, click the dropdown menu and the "Show Plugins" button to switch to the plugin rack and select the correct track.

**Comment by stargateaudio** [comment]
...and also, I have plans to add the ability to send a test sound to the selected device in the hardware dialog which should help with selecting the device, but that will be a significant effort that will come later, the current design won't easily allow that.

**Comment by stargateaudio** [comment]
> ...and also, I have plans to add the ability to send a test sound to the selected device in the hardware dialog which should help with selecting the device, but that will be a significant effort that will come later, the current design won't easily allow that.

I figured out a clever way to do this without re-writing the entire hardware dialog.  In the latest `main` branch or the next release, you will be able to send a test sound to your audio device before leaving the hardware dialog.

**Comment by stargateaudio** [comment]
@danboid 
> When I have the VA synth plugin window open and in focus, should I be abler to preview notes by pushing keys on the keyboard (QWERTYUIOP and the numbers above at least)? I also expect I should hear something when I click on notes on the keyboard to the left of the MIDI editor window?

QWERTYIOUP[] MIDI keyboard is implemented, will be in the next release.  There is also an octave spinbox on the plugin racks tab to change the octave, it plays the currently selected plugin rack

**Comment by stargateaudio** [comment]
@jagoly , I implemented a "Test" button on the hardware dialog that can help troubleshoot audio issues without having to open the main app, it will be in the next release, probably tomorrow.  Also, please send me the errors and warnings you are receiving.

**Comment by danboid** [comment]
Thanks for adding the QWERTY MIDI keyboard! This has been a standard thing since the Amiga tracker days :)

**Comment by jagoly** [comment]
apologies, was trying to make sure I didn't do anything dumb (I'm still not convinced I didn't), but anyway here is my [stargate.log](https://github.com/stargateaudio/stargate/files/7490264/stargate.log). I did delete the old stuff first, so this log should just be of me starting up the application, trying to play some sound, then changing the audio device again, which caused the program to quit but fail to restart.

possibly of interest is "[2021-11-06 21:36:54,704] WARNING /usr/lib/stargate/stargate/sgui/widgets/hardware_dialog.py: 184 - Could not find libportmidi.so.0", but the package portmidi-236-1 is installed.

Also, another thing I just noticed, all of the alsa devices listed were HDMI? It didn't seem to list the intel PCH sound device?

Whatever the issue is, being able to play test sound from the hardware chooser would definitely help.

**Comment by danboid** [comment]
> Also, another thing I just noticed, all of the alsa devices listed were HDMI? It didn't seem to list the intel PCH sound device?

I've also seen this happen. I think I had to reboot to fix the selection of devices but I expect there was a quicker and easier way to fix it.

**Comment by jagoly** [comment]
> > Also, another thing I just noticed, all of the alsa devices listed were HDMI? It didn't seem to list the intel PCH sound device?
> 
> I've also seen this happen. I think I had to reboot to fix the selection of devices but I expect there was a quicker and easier way to fix it.

Yeah, I'm 90% sure they were listed the other day, not sure what could have changed?

**Comment by mikobuntu** [comment]
I'm adding my findings here instead of opening a new thread as I believe this is somewhat related.... anyway...
I'm running kernel Linux mx 5.9.1-rt20avl1 #1 SMP PREEMPT_RT Sat Oct 31 12:21:58 EDT 2020 x86_64 GNU/Linux on AV_LInux. 
Stargate finds my Audio card settings no problem, but fails to make the actual connections. The 'test' fails with what I believe to be `GLIBC_2.29' not found'  
I have tested on both the Ubuntu and Debian .deb install files. The GUI is fully functional tho.
Thanks and do let me know how I can help with testing.

**Comment by stargateaudio** [comment]
@mikobuntu :  MX Linux is based on an older version of Debian, the Debian 11 and Ubunu 20.04 packages do not work on MX Linux because they were compiled against a more recent glibc.  At the moment, the best option to build a .deb package yourself, which is relatively easy to do:
https://github.com/stargateaudio/stargate/blob/main/docs/building.md

I will consider building the Debian packages against Debian 10 instead of Debian 11 to address this

**Comment by stargateaudio** [comment]
@mikobuntu :  Latest release is built on Debian 10, and is confirmed to work on MX Linux.

**Comment by stargateaudio** [comment]
@jagoly :  Sorry for missing your last comments. If Portaudio does not list a device, that usually means it is being used by something else at the time it was listing devices.  It depends on which audio backends your host has installed, and how they are configured.

The errors in the logs look like a Jack problem?
```
[2021-11-06 21:34:31,617] ERROR /usr/lib/stargate/stargate/sglib/lib/process.py: 55 - SUBPROCESS: "Cannot connect to server socket err = No such file or directory"
[2021-11-06 21:34:31,617] ERROR /usr/lib/stargate/stargate/sglib/lib/process.py: 55 - SUBPROCESS: "Cannot connect to server request channel"
```
